name: Test

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 12.20.1
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build cooper-ui
